# Generated by Django 3.0.1 on 2021-05-08 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='category',
        ),
    ]
