# Generated by Django 3.0.1 on 2021-05-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_remove_todos_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
